Repository SulePostar/finetica, pull requests merged in 2025-09, with the labels that each got.

#119 Feature/frontend restyling
  client/index.html
  client/public/symphonypurple.png
  client/src/_nav.js
  client/src/components/AppHeader.css
  client/src/components/AppHeader.jsx
  client/src/components/Sidebar/AppSidebar.css
  client/src/components/Sidebar/AppSidebar.jsx
  client/src/components/Sidebar/AppSidebarNav.jsx
  client/src/components/Sidebar/SidebarDriveStatus.jsx
  client/src/components/Sidebar/SidebarNavGroup.jsx
  client/src/components/Sidebar/SidebarNavItem.jsx
  client/src/components/Sidebar/SidebarNavLinkContent.jsx
  client/src/components/Tables/DynamicTable.styles.js
  client/src/components/header/AppHeaderDropdown.css
  client/src/components/header/AppHeaderDropdown.jsx
  client/src/hooks/useFilteredNavigation.js
  client/src/scss/style.scss
  client/src/styles/colors.js
Labels: enhancement

#104 refactor/kuf-prompt
  server/prompts/Kuf.js
  server/services/kuf.js
Labels: bug, enhancement, draft

#140 refactor/manual-file-upload
  client/src/components/Modals/FileUploadModal.jsx
  client/src/services/api.js
  server/.env.example
Labels: bug, enhancement, fix

#145 Refactor/disable email change
  client/src/components/Profile/ProfileForm.jsx
  client/src/services/userService.js
  server/services/users.js
Labels: enhancement

#164 refactor/file-upload-modal
  client/src/components/Modals/FileUploadModal.css
  client/src/components/Modals/FileUploadModal.jsx
  client/src/components/Register/ProfilePhotoUpload/ProfilePhotoUpload.jsx
  client/src/components/Register/ProfilePhotoUpload/ProfilePhotoUpload.styles.css
Labels: enhancement

#168 refactor/profile-form
  client/src/components/Profile/ProfileForm.css
Labels: fix

#170 Feature/reusable buttons
  client/src/components/ActionButtons/ActionButtons.jsx
  client/src/components/AppButton/AppButton.css
  client/src/components/AppButton/AppButton.jsx
  client/src/components/AppHeader.jsx
  client/src/components/InfoCards/DocumentInfo/DocumentInfo.jsx
  client/src/components/InvalidPdfDetails/InvalidPdfDetails.jsx
  client/src/components/Login/ForgotPasswordForm.jsx
  client/src/components/Login/LoginForm.jsx
  client/src/components/Login/ResetPasswordForm.jsx
  client/src/components/Modals/ConfirmationModal/ConfirmationModal.jsx
  client/src/components/Modals/FileUploadModal.jsx
  client/src/components/Modals/ViewUserModal/ViewUserModal.css
  client/src/components/Modals/ViewUserModal/ViewUserModal.jsx
  client/src/components/PdfViewer/PdfViewer.jsx
  client/src/components/Profile/ProfileForm.css
  client/src/components/Profile/ProfileForm.jsx
  client/src/components/Register/Form/RegisterForm.jsx
  client/src/components/Register/Form/RegisterForm.styles.js
  client/src/components/Register/ProfilePhotoUpload/ProfilePhotoUpload.jsx
  client/src/components/Tables/RolesStatusesTable.css
  client/src/components/Tables/RolesStatusesTable.jsx
  client/src/components/UploadButton/UploadButton.jsx
  client/src/components/Users/UserRow.jsx
  client/src/pages/DocumentDetails/DocumentDetails.jsx
  client/src/pages/DocumentDetails/DocumentItemsPage.jsx
  client/src/utilis/SearchFilters/SearchFilters.css
  client/src/utilis/SearchFilters/SearchFilters.jsx
Labels: enhancement, good first issue, feature

#171 Fixed import
  client/src/components/Modals/EditItemModal.jsx
Labels: bug

#174 Refactor/invalid pdfs
  client/src/components/AppButton/AppButton.jsx
  client/src/components/InvalidPdfDetails/InvalidPdfDetails.jsx
  client/src/components/PdfViewer/PdfViewer.jsx
  client/src/components/Tables/DynamicTable.jsx
  client/src/pages/invalidPdfs/InvalidPdfs.css
  client/src/pages/invalidPdfs/InvalidPdfs.jsx
Labels: enhancement, fix
